

export default function (lang) {
  if (lang === 'pt') {
    return {
      mobile: 'Mobile',
      accountDontHave: 'Não tem uma conta? pressione aqui',
      accountHave: 'Se já tiver uma conta clique aqui',
      invalidNif: 'O NIF introduzido não é válido',
      invalidPassword: 'A palavra-passe não é válida. Insira pelo menos 8 caracteres',
      invalidUsername: 'O nome de utilizador que escolheu não é válido',
      invalidEmail: 'O email introduzido não é válido',
      loginPage: 'Entrar',
      registerPage: 'Registar',
      insertValidParams: 'Por favor insira parametros válidos',
      thereWasAnError: 'Houve um erro, por favor tente novamente',
      name: 'Nome',
      password: 'Palavra Passe',
      confirmation: 'Confirmação',
      areSure: 'Tem a certeza que deseja prosseguir?',
      yes: 'Sim',
      no: 'Não',
      noPossibleToUpdateEvent: 'Não é posível atualizar o evento',
      confirmItWasYou: 'Deseja confirmar o evento?',
      payEvent: 'Proceder ao pagamento',
      eventVerified: 'O evento foi confirmado',
      eventOccurred: 'O evento occorreu no dia ',
      location: 'Localização',
      showMap: 'Mostrar mapa com a localização',
      hours: 'Hora',
      price: 'Preço',
      confirmPayment: 'Confirmar o pagamento',
      notValidUser: 'Utilizador inválido',
      tryAgain: 'Tentar novamente',
      cancel: 'Cancelar',
      error: 'Erro',
      ownerIdentification: 'Identificação do dono do veiculo',
      accept: 'Aceitar',
      deny: 'Recusar',
      vehicleRegistered: 'Este veículo foi registado a',
      removeVehicle: 'Remover veículo',
      yourId: 'A sua identificação',
      vehiclePlate: 'A matricula do veículo',
      sharingUserIdentification: 'A identificação do utilizador a realizar a partilha',
      shareVehicle: 'Partilhar vehiculo',
      acceptProcessTerms: 'Este processo terá de ser aceite pelo utilizador pretendido e poderá ser cancelado a qualquer momento!',
      cancelDelegation: 'Cancelar a delegação',
      cancelRequest: 'Cancelar o pedido',
      vehicleBorrowed: 'O veículo foi emprestado a outro utilizador',
      waitingBorrowConfirmation: 'O veiculo tem um empréstimo pendente',
      notBorrowed: 'O veículo não se encontra emprestado',
      unsubscribe: 'Cancelar subscrição do veículo',
      alreadySubscribed: 'O veículo já se encontra subscrito',
      subscribe: 'Subscrever veículo',
    };
  }
  return {
    mobile: 'Mobile',
    accountDontHave: "Don't Have an account? Click Here",
    accountHave: 'Already have an account? Click Here',
    invalidNif: 'Invalid NIF',
    invalidPassword: 'Invalid password. Insert 8 or more characters',
    invalidUsername: 'Invalid Username',
    invalidEmail: 'Invalid Email',
    loginPage: 'Login Page',
    registerPage: 'Register Page',
    insertValidParams: 'Please insert valid params',
    thereWasAnError: 'There was an error',
    name: 'Name',
    password: 'Password',
    confirmation: 'Confirmation',
    areSure: 'Are you sure?',
    yes: 'yes',
    no: 'no',
    noPossibleToUpdateEvent: 'It is not possible to update event',
    confirmItWasYou: 'Confirm that it was you?',
    payEvent: 'Proceed to event payment',
    eventVerified: 'This event is verified',
    eventOccurred: 'This event occurred on',
    hours: 'Hours',
    location: 'location',
    showMap: 'Show on map',
    price: 'Price',
    confirmPayment: 'Confirm Payment',
    notValidUser: 'Invalid User',
    tryAgain: 'Try again',
    cancel: 'Cancel',
    error: 'error',
    accept: 'Accept',
    deny: 'Deny',
    ownerIdentification: 'Owner Identification',
    vehicleRegistered: 'This vehicle was registered on',
    removeVehicle: 'Remove vehicle',
    yourId: 'Your Identification',
    vehiclePlate: 'Vehicle Plate',
    sharingUserIdentification: 'Sharing user identification',
    shareVehicle: 'Share vehicle',
    acceptProcessTerms: 'This process needs to be accepted by the pretended user, and can be canceled any time!',
    cancelDelegation: 'Cancel delegation',
    cancelRequest: 'Cancel request',
    vehicleBorrowed: 'This vehicle is borrowed',
    waitingBorrowConfirmation: 'This vehicle is waiting for borrow conformation',
    notBorrowed: 'This vehicle is not borrowed',
    unsubscribe: 'Unsubscribe vehicle',
    alreadySubscribed: 'This vehicle is already subscribed',
    subscribe: 'Subscribe vehicle',
  };
}

/* {
  en: {
    mobile: 'Mobile',
    accountDontHave: "Don't Have an account? Click Here",
  },
  pt: {
    mobile: 'Mobile',
    accountDontHave: 'Não tem uma conta? pressione aqui',
  },

};
*/
